[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify,.next"
  SECRETS_SCAN_OMIT_KEYS = "ADMIN_PASSWORD,ADMIN_SECRET_KEY,ADMIN_USERNAME,TELEGRAM_BOT_TOKEN,TELEGRAM_CHAT_ID,SEO_MANAGER_USERNAME,SEO_MANAGER_PASSWORD,DEEPSEEK_API_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
